# Generated by labproj from analysis.ipynb

# %% [markdown]
# # ANA-003: RUN-010 Raw-Scale Latent Observation Calibration Review
#
# Review RUN-010 against HYP-001 by testing whether coordinate-aware calibration on a homogeneous multi-mutant ProteinGym stability panel improves recovery of local landscape statistics.

# %% [markdown]
# ## Linked experiments/runs
#
# - Experiments: EXP-003
# - Runs: RUN-010

# %%
from pathlib import Path

analysis_dir = Path.cwd().resolve().parent
artifact_dir = analysis_dir / 'artifacts'
print(f'Analysis directory: {analysis_dir}')
if artifact_dir.exists():
    for path in sorted(artifact_dir.rglob('*')):
        if path.is_file():
            print(path.relative_to(analysis_dir))

# %% [markdown]
# ## Main observations
#
# - Add observations here.
