# Generated by labproj from analysis.ipynb

# %% [markdown]
# # ANA-002: RUN-008 Uncalibrated Single and Double DFE Grid Review
#
# Review RUN-008 as an indirect scope check under HYP-001 by summarizing whether the uncalibrated Adapt-Env model family spans plausible one-step and two-step mutational effect regimes before any empirical DMS fitting.

# %% [markdown]
# ## Linked experiments/runs
#
# - Experiments: EXP-002
# - Runs: RUN-008

# %%
import json
from pathlib import Path

import pandas as pd

analysis_dir = Path.cwd().resolve().parent
run_dir = Path.cwd().resolve().parents[2] / 'data' / 'processed' / 'uncalibrated-dfe-grid-scan-single-double-mutants' / 'RUN-008'
summary = json.loads((run_dir / 'summary.json').read_text())
per_setting = pd.read_csv(run_dir / 'single_double_dfe_per_setting.csv')

summary['results']['summary']

# %% [markdown]
# ## Inputs
#
# - `data/processed/uncalibrated-dfe-grid-scan-single-double-mutants/RUN-008/summary.json`
# - `data/processed/uncalibrated-dfe-grid-scan-single-double-mutants/RUN-008/single_double_dfe_per_setting.csv`
# - `data/processed/uncalibrated-dfe-grid-scan-single-double-mutants/RUN-008/single_double_dfe_per_landscape.csv`
# - `experiments/2026-05-08_EXP-002_uncalibrated-dfe-grid-scan-single-double-mutants/config.yaml`
# - `experiments/2026-05-08_EXP-002_uncalibrated-dfe-grid-scan-single-double-mutants/runs/RUN-008.yaml`

# %%
per_setting[
    [
        'setting_id',
        'single_fraction_neutral_mean',
        'single_fraction_lethal_mean',
        'double_fraction_lethal_mean',
        'double_fraction_beneficial_mean',
        'epistasis_abs_mean_mean',
    ]
].sort_values('epistasis_abs_mean_mean', ascending=False).head()

# %% [markdown]
# ## Main observations
#
# - `RUN-008` completed successfully across `81` grid settings and `324` landscapes total.
# - Doubles were more deleterious than singles in every setting, and more lethal in `83.3%` of settings.
# - `stability_margin` was the dominant harshness knob: lower margins sharply increased double lethality and epistasis magnitude.
# - `functional_sigma_base` mostly changed the single-mutant DFE, while `epistasis_strength` mainly changed double-mutant epistasis and left single-mutant neutrality unchanged.
# - The scan demonstrates broad local DFE capacity, but it is not an empirical realism test and therefore only motivates `HYP-001`.
