# Generated by labproj from analysis.ipynb

# %% [markdown]
# # ANA-012: RUN-028 paired KRAS abundance-binding thermodynamic diagnostic review
#
# Assess whether the EXP-009 paired KRAS abundance-plus-binding thermodynamic readout improves empirical recovery relative to binding-only and paired raw-readout controls, and determine the implication for HYP-007.

# %% [markdown]
# ## Linked experiments/runs
#
# - Experiments: EXP-009
# - Runs: RUN-028

# %%
from pathlib import Path

analysis_dir = Path.cwd().resolve().parent
artifact_dir = analysis_dir / 'artifacts'
print(f'Analysis directory: {analysis_dir}')
if artifact_dir.exists():
    for path in sorted(artifact_dir.rglob('*')):
        if path.is_file():
            print(path.relative_to(analysis_dir))

# %% [markdown]
# ## Main observations
#
# - Add observations here.
