# Generated by labproj from analysis.ipynb

# %% [markdown]
# # ANA-004
#
# Notebook record for `RUN-012 predictive-joint calibration and pairwise-capacity review`.

# %%
from pathlib import Path
import pandas as pd

run_dir = Path('data/processed/proteingym-predictive-joint-calibration-pairwise-capacity-panel/RUN-012')
branch_validations = pd.read_csv(run_dir / 'branch_validations.csv')
per_assay_branch_fits = pd.read_csv(run_dir / 'per_assay_branch_fits.csv')
mavenn_assay_metrics = pd.read_csv(run_dir / 'mavenn_assay_metrics.csv')
branch_validations
