# Generated by labproj from analysis.ipynb

# %% [markdown]
# # ANA-018: RUN-051 OXDA expression-activity paired latent trait diagnostic review
#
# Assess whether the EXP-018 paired OXDA expression/activity diagnostic supports a two-trait state/function calibration over a function-only single-trait fit.

# %% [markdown]
# ## Linked experiments/runs
#
# - Experiments: EXP-018
# - Runs: RUN-051

# %% [markdown]
# ## Inputs
#
# - data/processed/proteingym-oxda-expression-activity-paired-latent-trait-diagnostic/RUN-051/summary.json
# - data/processed/proteingym-oxda-expression-activity-paired-latent-trait-diagnostic/RUN-051/branch_validations.csv
# - data/processed/proteingym-oxda-expression-activity-paired-latent-trait-diagnostic/RUN-051/mavenn_assay_metrics.csv
# - data/processed/proteingym-oxda-expression-activity-paired-latent-trait-diagnostic/RUN-051/paired_readout_correlations.csv

# %% [markdown]
# ## Main observations
#
# - RUN-051 completed on lab-slurm as scheduler job 194 with exit code 0.
# - The matched OXDA expression/activity readouts had Spearman 0.246 over 6387 variants.
# - MAVE-NN test Spearman was 0.567 for expression and 0.542 for activity, so the observation layer was moderate rather than strong.
# - The function-only branch reached activity holdout Spearman 0.183, while the paired single-trait and explicit two-trait branches reached 0.061 and 0.180.
# - All branches placed the reference effectively at the peak and fitted zero epistasis, zero empirical pairwise strength, and zero noise.
# - The paired state/function branches therefore did not improve the primary single-mutant activity recovery package.

# %% [markdown]
# ## Produced artifacts
#
# - tables/run-051_key_metrics.md
