# Generated by labproj from analysis.ipynb

# %% [markdown]
# # ANA-017: RUN-043 PHOT oracle global-epistasis baseline review
#
# Assess whether the EXP-017 oracle additive latent score plus flexible monotone global-epistasis baseline outperforms recent mechanistic PHOT variants, thereby distinguishing restrictive AdaptEnv latent priors from scalar-assay measurement or identifiability limits.

# %% [markdown]
# ## Linked experiments/runs
#
# - Experiments: EXP-017
# - Runs: RUN-043

# %%
from pathlib import Path

analysis_dir = Path.cwd().resolve().parent
artifact_dir = analysis_dir / 'artifacts'
print(f'Analysis directory: {analysis_dir}')
if artifact_dir.exists():
    for path in sorted(artifact_dir.rglob('*')):
        if path.is_file():
            print(path.relative_to(analysis_dir))

# %% [markdown]
# ## Main observations
#
# - Add observations here.
