# Generated by labproj from analysis.ipynb

# %% [markdown]
# # ANA-001: RUN-006 ProteinGym Distributional Realism Review
#
# Review RUN-006 against HYP-001 by comparing the fitted shared Adapt-Env regime to ProteinGym single-mutant assay summary statistics and recording whether the observed evidence supports, weakens, or refutes the hypothesis.

# %% [markdown]
# ## Linked experiments/runs
#
# - Experiments: EXP-001
# - Runs: RUN-006

# %%
import json
from pathlib import Path

project_root = Path.cwd().resolve()
while project_root.name != 'project-adapt-env' and project_root.parent != project_root:
    project_root = project_root.parent

summary_path = project_root / 'data/processed/proteingym-dms-distributional-realism-panel/RUN-006/summary.json'
panel_path = project_root / 'data/processed/proteingym-dms-distributional-realism-panel/RUN-006/selected_panel.csv'
payload = json.loads(summary_path.read_text())
print('summary:', summary_path)
print('panel:', panel_path)
print('fitted parameters:', payload['fitted_parameters'])
print('validation:', payload['calibration_validation'])

# %% [markdown]
# ## Inputs
#
# - `data/processed/proteingym-dms-distributional-realism-panel/RUN-006/summary.json`
# - `data/processed/proteingym-dms-distributional-realism-panel/RUN-006/selected_panel.csv`
# - `experiments/2026-05-07_EXP-001_proteingym-dms-distributional-realism-panel/config.yaml`
# - `experiments/2026-05-07_EXP-001_proteingym-dms-distributional-realism-panel/runs/RUN-006.yaml`

# %% [markdown]
# ## Main observations
#
# - `RUN-006` completed and produced the declared durable outputs plus 8 MMseqs-derived alignment FASTAs for the selected assays.
# - The panel contains 8 assays across 4 taxa and 27,249 single mutants, so this is a real cross-assay test of `HYP-001` rather than an internal synthetic-only check.
# - The shared fitted regime collapsed `epistasis_strength`, `empirical_pairwise_strength`, `noise_amplitude`, and `peak_distance_from_consensus` to zero, leaving a deterministic low-dimensional functional fit.
# - Holdout performance was weak (`holdout_spearman = 0.103`, `holdout_nrmse = 0.998`) and the functional KS distance remained large (`0.537`).
# - The synthetic score distributions systematically under-produced the beneficial upper tail and were more negatively skewed than the empirical assays.
# - Evidence therefore weakens `HYP-001` rather than supporting it.
