# Generated by labproj from analysis.ipynb

# %% [markdown]
# # ANA-014: RUN-040 PHOT explicit two-trait validation-objective replicate review
#
# Assess whether the EXP-014 explicit two-trait PHOT validation-objective replicate reproduces the RUN-036 failure pattern and record the implication for HYP-007.

# %% [markdown]
# ## Linked experiments/runs
#
# - Experiments: EXP-014
# - Runs: RUN-040

# %%
from pathlib import Path

analysis_dir = Path.cwd().resolve().parent
artifact_dir = analysis_dir / 'artifacts'
print(f'Analysis directory: {analysis_dir}')
if artifact_dir.exists():
    for path in sorted(artifact_dir.rglob('*')):
        if path.is_file():
            print(path.relative_to(analysis_dir))

# %% [markdown]
# ## Main observations
#
# - Add observations here.
