# Generated by labproj from analysis.ipynb

# %% [markdown]
# # ANA-019: RUN-053 KCNJ2 surface-function paired latent trait diagnostic review
#
# Assess whether the EXP-019 paired KCNJ2 surface/function diagnostic supports a two-trait state/function calibration over a function-only single-trait fit.

# %% [markdown]
# ## Linked experiments/runs
#
# - Experiments: EXP-019
# - Runs: RUN-053

# %% [markdown]
# ## Inputs
#
# - data/processed/proteingym-kcnj2-surface-function-paired-latent-trait-diagnostic/RUN-053/summary.json
# - data/processed/proteingym-kcnj2-surface-function-paired-latent-trait-diagnostic/RUN-053/branch_validations.csv
# - data/processed/proteingym-kcnj2-surface-function-paired-latent-trait-diagnostic/RUN-053/mavenn_assay_metrics.csv
# - data/processed/proteingym-kcnj2-surface-function-paired-latent-trait-diagnostic/RUN-053/paired_readout_correlations.csv

# %% [markdown]
# ## Main observations
#
# - RUN-053 completed on lab-slurm as scheduler job 196 with exit code 0.
# - The matched KCNJ2 surface/function readouts had Spearman 0.290 over 6789 variants.
# - MAVE-NN test Spearman was 0.538 for surface trafficking and 0.389 for function, so the function observation layer was weak.
# - The function-only branch reached function holdout Spearman 0.066, while the paired single-trait and explicit two-trait branches reached 0.065 and 0.021.
# - The paired explicit two-trait branch had marginally lower NRMSE but worse ranking and KS than the function-only branch.
# - All branches placed the reference near the peak and fitted zero epistasis, zero empirical pairwise strength, and zero noise.
# - The paired state/function branches therefore did not improve the primary single-mutant function recovery package.

# %% [markdown]
# ## Produced artifacts
#
# - tables/run-053_key_metrics.md
