# Generated by labproj from analysis.ipynb

# %% [markdown]
# # ANA-015: RUN-041 PHOT flexible monotone two-latent readout diagnostic review
#
# Assess whether the EXP-015 flexible monotone two-latent PHOT diagnostic improves held-out ranking and epistasis recovery relative to the explicit product/gate two-trait failure and the stability-targeted control.

# %% [markdown]
# ## Linked experiments/runs
#
# - Experiments: EXP-015
# - Runs: RUN-041

# %%
from pathlib import Path

analysis_dir = Path.cwd().resolve().parent
artifact_dir = analysis_dir / 'artifacts'
print(f'Analysis directory: {analysis_dir}')
if artifact_dir.exists():
    for path in sorted(artifact_dir.rglob('*')):
        if path.is_file():
            print(path.relative_to(analysis_dir))

# %% [markdown]
# ## Main observations
#
# - Add observations here.
