# Generated by labproj from analysis.ipynb

# %% [markdown]
# # ANA-011: RUN-038 single-assay stability-readout control calibration review
#
# Assess whether the simpler EXP-011 stability-targeted single-latent control recovers PHOT_CHLRE_Chen_2023 better than the recent PHOT activity-oriented formulations, and determine what that control implies for HYP-007.

# %% [markdown]
# ## Linked experiments/runs
#
# - Experiments: EXP-011
# - Runs: RUN-038

# %%
from pathlib import Path

analysis_dir = Path.cwd().resolve().parent
artifact_dir = analysis_dir / 'artifacts'
print(f'Analysis directory: {analysis_dir}')
if artifact_dir.exists():
    for path in sorted(artifact_dir.rglob('*')):
        if path.is_file():
            print(path.relative_to(analysis_dir))

# %% [markdown]
# ## Main observations
#
# - Add observations here.
