# Generated by labproj from analysis.ipynb

# %% [markdown]
# # ANA-010: RUN-036 explicit two-latent-trait validation-objective calibration review
#
# Assess whether the clean EXP-012 explicit two-latent-trait formulation improves empirical recovery on PHOT_CHLRE relative to the earlier PHOT implementations once the latent-trait confounders are removed and the Bayesian fit optimizes the held-out validation objective directly.

# %% [markdown]
# ## Linked experiments/runs
#
# - Experiments: EXP-012
# - Runs: RUN-036

# %%
from pathlib import Path

analysis_dir = Path.cwd().resolve().parent
artifact_dir = analysis_dir / 'artifacts'
print(f'Analysis directory: {analysis_dir}')
if artifact_dir.exists():
    for path in sorted(artifact_dir.rglob('*')):
        if path.is_file():
            print(path.relative_to(analysis_dir))

# %% [markdown]
# ## Main observations
#
# - Add observations here.
