# Generated by labproj from analysis.ipynb

# %% [markdown]
# # ANA-016: RUN-042 PHOT stability-first residual-trait sparse-residual diagnostic review
#
# Assess whether the EXP-016 stability-first residual-trait and sparse pair-residual PHOT diagnostic isolates additional readout structure beyond the stability component and improves held-out ranking or epistasis recovery.

# %% [markdown]
# ## Linked experiments/runs
#
# - Experiments: EXP-016
# - Runs: RUN-042

# %%
from pathlib import Path

analysis_dir = Path.cwd().resolve().parent
artifact_dir = analysis_dir / 'artifacts'
print(f'Analysis directory: {analysis_dir}')
if artifact_dir.exists():
    for path in sorted(artifact_dir.rglob('*')):
        if path.is_file():
            print(path.relative_to(analysis_dir))

# %% [markdown]
# ## Main observations
#
# - Add observations here.
