# Generated by labproj from analysis.ipynb

# %% [markdown]
# # ANA-006: RUN-022 single-assay Bayesian SMC-ABC calibration review
#
# Assess whether restricting the Bayesian SMC-ABC calibration to the single SPTN1_CHICK_Tsuboyama_2023_1TUD assay rescues empirical recovery enough to explain the earlier HYP-001 failure mainly as cross-assay pooling.

# %% [markdown]
# ## Linked experiments/runs
#
# - Experiments: EXP-006
# - Runs: RUN-022

# %%
from pathlib import Path

analysis_dir = Path.cwd().resolve().parent
artifact_dir = analysis_dir / 'artifacts'
print(f'Analysis directory: {analysis_dir}')
if artifact_dir.exists():
    for path in sorted(artifact_dir.rglob('*')):
        if path.is_file():
            print(path.relative_to(analysis_dir))

# %% [markdown]
# ## Main observations
#
# - Add observations here.
