# Generated by labproj from analysis.ipynb

# %% [markdown]
# # ANA-005: RUN-019 Bayesian shared-summary SMC-ABC calibration review
#
# Assess whether the resumed Bayesian SMC-ABC calibration in RUN-019 recovers the fixed six-assay ProteinGym stability panel more faithfully than the deterministic controls and whether synthetic-truth recovery supports the inference procedure.

# %% [markdown]
# ## Linked experiments/runs
#
# - Experiments: EXP-005
# - Runs: RUN-019

# %%
from pathlib import Path

analysis_dir = Path.cwd().resolve().parent
artifact_dir = analysis_dir / 'artifacts'
print(f'Analysis directory: {analysis_dir}')
if artifact_dir.exists():
    for path in sorted(artifact_dir.rglob('*')):
        if path.is_file():
            print(path.relative_to(analysis_dir))

# %% [markdown]
# ## Main observations
#
# - Add observations here.
