# Generated by labproj from analysis.ipynb

# %% [markdown]
# # ANA-007: RUN-024 single-assay stability-readout SMC-ABC calibration review
#
# Assess whether the stability-targeted synthetic readout in RUN-024 materially improves empirical recovery on SPTN1_CHICK_Tsuboyama_2023_1TUD relative to the earlier raw-readout single-assay Bayesian fit and deterministic controls.

# %% [markdown]
# ## Linked experiments/runs
#
# - Experiments: EXP-007
# - Runs: RUN-024

# %%
from pathlib import Path

analysis_dir = Path.cwd().resolve().parent
artifact_dir = analysis_dir / 'artifacts'
print(f'Analysis directory: {analysis_dir}')
if artifact_dir.exists():
    for path in sorted(artifact_dir.rglob('*')):
        if path.is_file():
            print(path.relative_to(analysis_dir))

# %% [markdown]
# ## Main observations
#
# - Add observations here.
