# Generated by labproj from analysis.ipynb

# %% [markdown]
# # ANA-008: Untitled analysis
#
# To be defined.

# %% [markdown]
# ## Linked experiments/runs
#
# - Experiments: None
# - Runs: None

# %%
from pathlib import Path

analysis_dir = Path.cwd().resolve().parent
artifact_dir = analysis_dir / 'artifacts'
print(f'Analysis directory: {analysis_dir}')
if artifact_dir.exists():
    for path in sorted(artifact_dir.rglob('*')):
        if path.is_file():
            print(path.relative_to(analysis_dir))

# %% [markdown]
# ## Main observations
#
# - Add observations here.
