# Generated by labproj from analysis.ipynb

# %% [markdown]
# # ANA-009: RUN-030 latent-activity observed-fitness calibration review
#
# Assess whether the EXP-010 latent-activity observed-fitness generator improves empirical recovery on PHOT_CHLRE relative to both its within-run controls and the earlier RUN-026 biophysical-function baseline.

# %% [markdown]
# ## Linked experiments/runs
#
# - Experiments: EXP-010
# - Runs: RUN-030

# %%
from pathlib import Path

analysis_dir = Path.cwd().resolve().parent
artifact_dir = analysis_dir / 'artifacts'
print(f'Analysis directory: {analysis_dir}')
if artifact_dir.exists():
    for path in sorted(artifact_dir.rglob('*')):
        if path.is_file():
            print(path.relative_to(analysis_dir))

# %% [markdown]
# ## Main observations
#
# - Add observations here.
