# Generated by labproj from analysis.ipynb

# %% [markdown]
# # ANA-013: RUN-039 PHOT stability-readout validation-objective control review
#
# Assess whether the EXP-013 PHOT stability-targeted control retains its predictive advantage when fitted with the held-out validation objective used in EXP-012, and record the implication for HYP-007.

# %% [markdown]
# ## Linked experiments/runs
#
# - Experiments: EXP-013
# - Runs: RUN-039

# %%
from pathlib import Path

analysis_dir = Path.cwd().resolve().parent
artifact_dir = analysis_dir / 'artifacts'
print(f'Analysis directory: {analysis_dir}')
if artifact_dir.exists():
    for path in sorted(artifact_dir.rglob('*')):
        if path.is_file():
            print(path.relative_to(analysis_dir))

# %% [markdown]
# ## Main observations
#
# - Add observations here.
